name: Tinybird CD

on:
  push:
    branches:
      - main
    paths:
      - "example/tinybird.config.*"
      - "example/tinybird.json"
      - "example/**/*.ts"

env:
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  tinybird:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "example"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: example/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tinybird:deploy
